#source("pipeline/load_cross_objects.R")
# main figures
dir.create("fig_final/main/staging/",recursive = T)
#dir.create("fig_final/svg/",recursive = T)
source("r_final/figure1_local.R")
source("r_final/figure2_byxrm_map.R")
source("r_final/figure3_trans_other_crosses.R")
source("r_final/figure4_noise_attempt2.R")
source("r_final/figure5_cell_cycle_interactions.R")
source("r_final/figure6_gpa1.R")
# Supplementary figures
source("r_final/figureS1_one_pot_diagram.R")
source("r_final/figureS2_pca_plots.R")
source("r_final/figureS3_cell_cycle_dependent.R")
source("r_final/figureS4_393_cell_cycle.R")
source("r_final/figureS5_393_cell_cycle2.R")
source("r_final/figureS6_hist_count_cells_393.R")
source("r_final/figureS7_correlation_between_umi_and_accuracy.R")
source("r_final/figureS8_genotype_accuracy.R")
source("r_final/figureS9_ase_diploids_correlation.R")
source("r_final/figureS10_simulations_negbin_ase.R")
source("r_final/figureS11_overall_trend.R")
source("r_final/figureS12_gpa1_single_cell.R")
source("r_final/figureS13_gpa_mating_assay.R")
source("r_final/figureS14_additional_strain_annotations.R")
source("r_final/figureS15_heterozygosity_assocation.R")

# Tables S1-S3 are made manually 
source("r_final/tableS4_dataset_summary.R")
source("r_final/tableS5_cell_cycle.R")
source("r_final/tableS6_393_eQTLs.R")
source("r_final/tableS7_eQTL_bulk.R")
source("r_final/tableS8_distal_eQTLs.R")
source("r_final/tableS9_ase_cc_interactions.R")
source("r_final/tables10_noise_ase.R")
source("r_final/tableS11_cell_cycle_associations.R")
source("r_final/tableS12_GPA1_single_cell_validation.R")

#source("r_final/tableS5_393_eQTLs.R")