#source("pipeline/load_cross_objects.R")
dir.create("fig_final/main/staging/",recursive = T)
dir.create("fig_final/svg/",recursive = T)
source("r_final/figure1_local.R")
source("r_final/figure2_byxrm_map.R")
source("r_final/figure3_trans_other_crosses.R")
source("r_final/figure4_noise_attempt2.R")
source("r_final/figure5_cell_cycle_interactions.R")
source("r_final/figure6_gpa1.R")

source("r_final/figureS1_one_pot_diagram.R")
source("r_final/figureS2_393_cell_cycle.R")
source("r_final/figureS3_393_cell_cycle2.R")
source("r_final/figureS4_hist_count_cells_393.R")
source("r_final/figureS5_correlation_between_umi_and_accuracy.R")
source("r_final/figureS6_genotype_accuracy.R")
source("r_final/figureS7_ase_diploids_correlation.R")
source("r_final/figureS8_simulations_negbin_ase.R")
source("r_final/figureS9_overall_trend.R")
source("r_final/figureS10_gpa1_single_cell.R")
source("r_final/figureS11_gpa_mating_assay.R")
source("r_final/figureS12_additional_strain_annotations.R")
source("r_final/figureS13_heterozygosity_assocation.R")

# Tables S1-S3 are made manually 
source("r_final/tableS4_dataset_summary.R")
source("r_final/tableS5_cell_cycle.R")
source("r_final/tableS6_393_eQTLs.R")
source("r_final/tableS7_eQTL_bulk.R")
source("r_final/tableS8_distal_eQTLs.R")
source("r_final/tableS9_ase_cc_interactions.R")
source("r_final/tables10_noise_ase.R")
source("r_final/tableS11_cell_cycle_associations.R")
source("r_final/tableS12_GPA1_single_cell_validation.R")

#source("r_final/tableS5_393_eQTLs.R")